name: FIA - GitHub Actions - Databricks

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-connection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Verify Databricks connection
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          echo "Verificando conexión con Databricks..."
          databricks workspace list /
          echo "Conexión con Databricks realizada correctamente."